### PR TITLE
Search with category endpoint

### PR DESCRIPTION
**Pull request by sic-f**
### Changes proposed in this pull request:
* Add endpoint for searching with a category
`Bees.Venue.category/7`

##### Categories:
https://developer.foursquare.com/docs/resources/categories

#### Screenshot:
search_for_venues_-_foursquare_developer

#### Ready for review:
@DanToml

### CODE REVIEW

**Comment by sic-f** [comment]
@DanToml *Rebased*. Thanks :star2: :dizzy:

**Comment by DanToml** [comment]
@sic-f That's great - thanks! - I also just setup CI so it's easier to validate future changes too.

**Comment by sic-f** [comment]
@DanToml No worries 🌟 Cool, easier now that we have CI 💯

**Comment by DanToml** [comment]
🎉 Gonna cut a 0.3.0 release when I get home tonight. 

Thanks for the great work

**Pull request merged**
