### PR TITLE
Add support for user details.

### PR DESCRIPTION
**Pull request by aliou**
👋🏾
This pull request adds a User struct and a method to retrieve a user details.
Let me know if I should update things / add more tests.
Thanks!

### CODE REVIEW

**Comment by DanToml** [comment]
This is great! - Thanks 💜

**Comment by aliou** [comment]
🙌🏾 Cool, thanks for merging! Do you think you could also bump the package version and update it on hex.pm?

**Comment by DanToml** [comment]
Yep, Will try and get a release out today

**Comment by DanToml** [comment]
Released 0.1.0 🎉 🎊  https://hex.pm/packages/bees/0.1.0

**Comment by aliou** [comment]
Coooool thanks!

**Pull request merged**
